defaults: &defaults
    # Database settings
    SQLALCHEMY_TRACK_MODIFICATIONS: false
    SQLALCHEMY_ENGINE_OPTIONS:
        pool_pre_ping: true
#    DB_PORT: 5432

    # User Model settings
    admin_role: "Admin"
    readonly_role: "User"

    # Complaint Form settings
    varchar_max: 100
    text_max: 5000
    date_format: "%b %d %Y, %I:%M %p"
    pollution_types:
        - "Odors/Fumes"
        - "Smoke"
        - "Dust"
        - "Asbestos"

    # Flask-Security overrides
    SECURITY_LOGIN_USER_TEMPLATE: "dashboard/login.html"
    SECURITY_UNAUTHORIZED_VIEW: "/dashboard/"

    # Email Template Settings
    COMPLAINT_SUBJECT: "Confirmation of Your Air Pollution Complaint"
    INVITE_SUBJECT: "Create Your Pollution Reports Organizer Account"
    RESET_PASSWORD_SUBJECT: "Reset Your Password on Pollution Reports"
    WELCOME_SUBJECT: "You Are Now an Organizer on Pollution Reports"
    RESET_SUCCESS_SUBJECT: "Your Password on Pollution Reports Was Changed"

    # Tell app which environment variables you care about.
    # This also serves as a reminder of what needs to go
    # into your .env when deploying
    LOAD_FROM_ENV:
        - "SECRET_KEY"
        - "SECURITY_PASSWORD_SALT"
        - "PLACES_API_KEY"
        - "DB_USERNAME"
        - "DB_PASSWORD"
        - "DB_SERVER"
        - "FLASK_ENV"
        - "DEFAULT_USER_EMAIL"
        - "DEFAULT_USER_PASSWORD"
        - "SENDGRID_API_KEY"
        - "SENDGRID_COMPLAINT_FROM"
        - "SENDGRID_ORGANIZER_FROM"

development:
    # General app settings
    TESTING: True
    DEBUG: True
    # Database settings
    DB_PREFIX: "sqlite:///"
    DB_NAME: "app.db"
    <<: *defaults

testing:
    # General app settings
    TESTING: True
    DEBUG: False
    # Database settings
    DB_PREFIX: "postgresql://"
    <<: *defaults

deployment:
    # General app settings
    TESTING: False
    DEBUG: False
    # Database settings
    DB_PREFIX: "postgresql://"
    <<: *defaults
