defaults: &defaults
    # Database settings
    SQLALCHEMY_TRACK_MODIFICATIONS: false
    SQLALCHEMY_ENGINE_OPTIONS:
        pool_pre_ping: true
    DB_PREFIX: "sqlite:///"
    DB_NAME: "app.db"

    # Model/Form settings
    varchar_max: 200
    text_max: 5000
    date_format: "%m/%d/%Y"
    pollution_types:
        - "Odors"
        - "Dust"
        - "Smoke"
        - "Asbestos"
        - "Gas Stations"
        - "Painting"
        - "Other Stationary Sources"

    # Default inputs for EPA form
    report_recipients: "Communities for a Better Environment, via pollutionreports.org"

    # Values specified in .env file or explicitly in env
    LOAD_FROM_ENV:
        - "SECRET_KEY"
        - "PLACES_API_KEY"
        - "FLASK_ENV"
        - "DEV_RECAPTCHA_PUBLIC_KEY"
        - "DEV_RECAPTCHA_SECRET_KEY"
        - "PROD_RECAPTCHA_PUBLIC_KEY"
        - "PROD_RECAPTCHA_SECRET_KEY"
        - "EPA_START_URL"
        - "EPA_URL_1"
        - "EPA_URL_2"
        - "EPA_URL_3"
        - "GSHEET_TEST"
        - "GSHEET_PROD"

    GSHEET_COLS: # Order of columns for google sheet
        - "first_name"
        - "last_name"
        - "phone"
        - "landline"
        - "email"
        - "privacy_contact_ok"
        - "anonymous"
        - "lat"
        - "lng"
        - "street_number"
        - "locality"
        - "route"
        - "administrative_area_level_1"
        - "administrative_area_level_2"
        - "postal_code"
        - "reporter_search"
        - "pollution_type"
        - "date"
        - "hour"
        - "minute"
        - "ampm"
        - "description"
        - "ongoing"
        - "refinery"
        - "polluter_name"
        - "polluter_lat"
        - "polluter_lng"
        - "polluter_street_number"
        - "polluter_route"
        - "polluter_locality"
        - "polluter_administrative_area_level_1"
        - "polluter_administrative_area_level_2"
        - "polluter_postal_code"
        - "polluter_search"

development:
    # General app settings
    TESTING: True
    DEBUG: True
    <<: *defaults

testing:
    # General app settings
    TESTING: True
    DEBUG: False
    <<: *defaults

deployment:
    # General app settings
    TESTING: False
    DEBUG: False
    <<: *defaults
