defaults: &defaults
    # Database settings
    SQLALCHEMY_TRACK_MODIFICATIONS: false
    SQLALCHEMY_ENGINE_OPTIONS:
        pool_pre_ping: true

    # Database settings
    DB_PREFIX: "sqlite:///"
    DB_NAME: "app.db"

    # Model/Form settings
    varchar_max: 100
    text_max: 5000
    date_format: "%b %d %Y, %I:%M %p"
    pollution_types:
        - "Odors/Fumes"
        - "Smoke"
        - "Dust"
        - "Asbestos"

    LOAD_FROM_ENV:
        - "SECRET_KEY"
        - "PLACES_API_KEY"
        - "DB_USERNAME"
        - "DB_PASSWORD"
        - "DB_SERVER"
        - "FLASK_ENV"

development:
    # General app settings
    TESTING: True
    DEBUG: True
    <<: *defaults

testing:
    # General app settings
    TESTING: True
    DEBUG: False
    <<: *defaults

deployment:
    # General app settings
    TESTING: False
    DEBUG: False
    <<: *defaults
