"""complaints

Revision ID: ae600bc4e543
Revises: 
Create Date: 2021-01-11 09:40:33.083945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae600bc4e543'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('confirm_email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=100), nullable=True),
    sa.Column('landline', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=5), nullable=True),
    sa.Column('type', sa.Enum('Odors/Fumes', 'Smoke', 'Dust', 'Asbestos'), nullable=False),
    sa.Column('description', sa.Text(length=5000), nullable=False),
    sa.Column('polluter_name', sa.String(length=100), nullable=True),
    sa.Column('polluter_address', sa.String(length=100), nullable=False),
    sa.Column('polluter_city', sa.String(length=100), nullable=False),
    sa.Column('polluter_state', sa.String(length=2), nullable=False),
    sa.Column('polluter_zip', sa.String(length=5), nullable=False),
    sa.Column('observed_date', sa.DateTime(), nullable=False),
    sa.Column('ongoing', sa.Boolean(), nullable=False),
    sa.Column('consent_to_followup', sa.Boolean(), nullable=False),
    sa.Column('consent_to_campaign', sa.Boolean(), nullable=False),
    sa.Column('submitted_date', sa.DateTime(), nullable=True),
    sa.Column('submitted_to_calepa', sa.Boolean(), nullable=True),
    sa.Column('submitted_to_calepa_date', sa.DateTime(), nullable=True),
    sa.Column('calepa_confirmation_number', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint')
    # ### end Alembic commands ###
